# Generated by Django 4.0.5 on 2022-06-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
