# Generated by Django 4.0.5 on 2022-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0003_remove_customer_phone_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executor',
            name='is_executor',
            field=models.BooleanField(default=True),
        ),
    ]
