# Generated by Django 4.0.5 on 2022-06-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_alter_customer_is_executor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='password',
        ),
    ]
