# Generated by Django 4.0.5 on 2022-06-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_remove_customer_password_remove_executor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='executor',
            name='email',
        ),
    ]
