# Generated by Django 4.0.5 on 2022-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('1', 'Веб розробка'), ('2', 'Маркетинг'), ('3', 'Копірайтинг'), ('4', 'Рерайтинг'), ('5', 'Переклади'), ('6', 'Відеомонтаж'), ('7', 'Фотографія')], max_length=1),
        ),
    ]
